habitStruct.AK1951.name = 'Aufm Kampe et al. 1951';
habitStruct.AK1951.temp = 0:-1:-40;
habitStruct.AK1951.ice_s = zeros(1,40);
habitStruct.AK1951.habit = {'plates','plates','plates','plates, single clear plates, single prisms, twin prisms, hollow prisms, needles', ...
    'single clear plates, single prisms, twin prisms, hollow prisms, needles', 'single clear plates, single prisms, twin prisms, hollow prisms, needles, columns', ...
    'columns', 'columns', 'columns', 'columns, plates with ribs, single clear plates', 'columns, plates with ribs, single clear plates', 'columns, plates with ribs, single clear plates', ...
    'columns, plates with ribs, single clear plates', 'plates with ribs', 'plates with ribs', 'plates with ribs, plates, dendrites/stars', ...
    'plates, dendrites/stars', 'plates, dendrites/stars', 'plates, dendrites/stars, irregular aggregates', 'irregular aggregates', 'irregular aggregates', ...
    'columns, aggregates of columns/plates'};
coldAK = repmat('columns, aggregates of columns/plates',20,1);
